version: "3"

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb-yourfinances
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your-finances
      MONGO_INITDB_ROOT_PASSWORD: yourFinances123
      MONGO_INITDB_DATABASE: your-finances-auth
    networks:
      - mongo-db-network
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db

networks:
  mongo-db-network:
    driver: bridge

volumes:
  mongodb-data:
